"use strict";
const Qinglangshipinfengkongpingtai_vue_vue_type_style_index_0_scoped_575236ed_lang = "";
module.exports = Qinglangshipinfengkongpingtai_vue_vue_type_style_index_0_scoped_575236ed_lang;
